# Generated by Django 3.0.5 on 2020-07-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Album')),
                ('data', models.DateTimeField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('segundos', models.IntegerField(verbose_name='Segundos')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.Albun')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='albun',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.Banda'),
        ),
    ]
